name: Deploy Nuxt App to IIS via SFTP

on:
  push:
    branches: [master] # Or change to your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Site
        run: npm run generate

      - name: Deploy to IIS via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 400
          source: "dist"
          target: "C:/inetpub/wwwroot/Bozor.Frontend"
